### ISSUE TITLE
WAB widgets working without anything code change

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-wab-widgets#1]
https://github.com/USEPA/Public_Web_AppBuilder/tree/master/widgets/BombThreat

```
        BombThreat: {
            include: true,
            id: 'BombThreat',
            type: 'titlePane',
            position: 16,
            title: 'BombThreat',
            open: false,
            path: 'jimu/BaseWidgetPanel',
            options: {
                widgetManager: true,
                config: {
                    widgets: [
                        {
                            id: 'WABBombThreat',
                            uri: 'widgets/BombThreat/Widget'
                        }
                    ]
                }
            }
        },              
```

**Comment by ERS-Long** [comment]
PrintPlus is also working.

https://github.com/USEPA/Public_Web_AppBuilder/tree/master/widgets/PrintPlus

The only issue with this one is it is showing the print plus outline by default. I could not figure out how to change that. If I go into the file config.json in that widget to change 

  "showLayout": true,  to  
  "showLayout": false,

Then it will not show the outline anymore. 

I dont know if that is the bug in that widget or something i could missed.

            PrintPlus: {
                include: true,
                id: 'PrintPlus',
                type: 'titlePane',
                position: 19,
                title: 'PrintPlus',
                open: false,
                path: 'jimu/BaseWidgetPanel',
                options: {
                    widgetManager: true,
                    config: {
                        widgets: [
                            {
                                id: 'WABPrintPlus',
                                uri: 'widgets/PrintPlus/Widget'
                            }
                        ]
                    }
                }
            },

**Comment by ERS-Long** [comment]
elpaso is also working with no change needed

https://github.com/USEPA/Public_Web_AppBuilder/tree/master/widgets/elpaso

            elpaso: {
                include: true,
                id: 'elpaso',
                type: 'titlePane',
                position: 20,
                title: 'elpaso',
                open: false,
                path: 'jimu/BaseWidgetPanel',
                options: {
                    widgetManager: true,
                    config: {
                        widgets: [
                            {
                                id: 'WABelpaso',
                                uri: 'widgets/elpaso/Widget'
                            }
                        ]
                    }
                }
            },

**Comment by tmcgee** [comment]
Nice!

**Comment by ERS-Long** [comment]
Another one is working out of the box -- ERG

https://github.com/Esri/solutions-webappbuilder-widgets/tree/master/ERG

            ERG: {
                include: true,
                id: 'ERG',
                type: 'titlePane',
                position: 11,
                title: 'ERG',
                canFloat: true,
                resizable: true, // This widget is resizable when floating
                open: false,
                path: 'jimu/BaseWidgetPanel', // Note the path
                options: {
                    // use the WAB WidgetManager (required)
                    widgetManager: true,

                    // This widget requires some height to work properly
                    style: 'height:680px;',

                    config: {
                        widgets: [
                            {
                                id: 'ERGWABWidget',
                                uri: 'widgets/ERG/Widget'  // Note the path
                            }
                        ]
                    }
                }
            },

**Comment by tmcgee** [comment]
The list may be shorter if we identify which widgets DON'T work. :)

**Comment by ERS-Long** [comment]
that is right!
