### ISSUE TITLE
3.17 API Update

### ISSUE THREAD

**Issue by cmccullough2** [tmcgee/cmv-wab-widgets#3]
Will you be migrating this application to the 3.17 API in the near future?

**Comment by tmcgee** [comment]
@cmccullough2 I am using the 3.17 api without issue. This is in multiple apps for a couple of my clients.

**Comment by cmccullough2** [comment]
Thank you.  I am going to start my migration to 3.17.

**Comment by cmccullough2** [comment]
![3 17popupissue](https://cloud.githubusercontent.com/assets/3169799/17981613/01a28140-6aca-11e6-865d-a368fea6f138.PNG)
For some reason when I moved to the 3.17 api, this image appeared in my viewer.  I.E's Dom explorer is not giving me any clues.  Have you seen this before?

**Comment by tmcgee** [comment]
I have not seen that before. The Chrome Dev Tools might be a better tool to inspect the DOM for additional clues.

**Comment by cmccullough2** [comment]
Thanks.  I am looking.

**Comment by tmcgee** [comment]
@cmccullough2 The repo has been updated to version 3.17 of the Esri JavaScript API. The latest update also provides support for version 2.1 of WebApp Builder.

**Comment by cmccullough2** [comment]
Double thumbs up.  Thanks

**Comment by cmccullough2** [comment]
@tmcgee When you store the esri.css locally it breaks a bunch of images.  I went into the css file and changed the location of images from ../dijit/images/{image} to ..images/{image} to repair the paths.  I am a bit nervous about what this will do for future widget installs, etc.  (the unknown).  Just a thought.

**Comment by tmcgee** [comment]
Yes if you do not download the images, it would break due to the image paths in the css file. The most common practice for hosting locally is to download the entire JS API which includes everything. Is that not what you are doing?

**Comment by cmccullough2** [comment]
Yes, I am using the entire JS API.  When I need to have the API off my work network I am hosting the API at this location, http://gissweetspot.com/arcgis_js_api/library/3.17/3.17/init.js.  The location for the esri.css is here,   <link rel="stylesheet" type="text/css" href="./cmv/css/esri.css">.  While I am at work, I have it at another location.

**Comment by tmcgee** [comment]
The path to your esri.css does not appear in your message above but I see in in the notification I receive.

I am not following why you have the esri css file under the cmv folder - a different location from the rest of the API. Are you making some customizations within it? If so, typically, you use the one in the API location and include your own custom css overrides in a separate css file like [this](https://github.com/cmv/cmv-app/blob/master/viewer/css/main.css#L244)

**Comment by cmccullough2** [comment]
I have the esri.css in the cmv/css folder within the project.  the JS API is outside.  I am assuming I have to put the css someplace else??

**Comment by tmcgee** [comment]
I guess I don't understand why you have the esri.css separate from the JS API. If possible, you should try to keep the css file together with the API and then put any css customizations in a separate file within the project.

**Comment by cmccullough2** [comment]
Ok, good advice.  Under what folder in the api should the css reside.

**Comment by cmccullough2** [comment]
Nevermind.  That was a dumb question.  I figured it out.  I was making this harder than I needed to.

**Comment by tmcgee** [comment]
The file should already be included with the api however I see that it is not there on the gissweetspot.com server. That suggests that gissweetspot does not have a complete copy of the API (or I am missing something).

Obviously, I cannot see what you are using inside your network. When you are outside your network, can you use `//js.arcgis.com/3.17/esri/css/esri.css` and `//js.arcgis.com/3.17/` instead of the gissweetspot.com?
