### ISSUE TITLE
defaultMapClickMode: 'identify' not working by default.

### ISSUE THREAD

**Issue by triesco** [tmcgee/cmv-wab-widgets#4]
The defaultMapClickMode: 'identify', may not be working by default or at least it does not identify a feature by clicking on it when map is first opened, instead it will work with the right click and then identify.

**Comment by tmcgee** [comment]
@triesco Of the several clients that I have using this version of cmv, none have this issue. Could it be one of the WAB widgets that is interfering?

**Comment by triesco** [comment]
Yes, i think it is. I think is that easearch widget. Cant find where is
interfering thou. Grrrrr!! Heheh

**Comment by triesco** [comment]
Sorry, think i found it on the widget.js on post create.

For the other issue loading the widget and cutting the top any suggestions
you can provide?

**Comment by triesco** [comment]
Yes, found it. It was interfering with the esearch widget.
