### ISSUE TITLE
Basemap Gallery in sidebar Right panel

### ISSUE THREAD

**Issue by cmccullough2** [tmcgee/cmv-wab-widgets#5]
I want to put the basemap gallery in the right side panel.  The panel displays, but the widget does not.  Any suggestions?
right: {
                id: 'sidebarRight',
                placeAt: 'outer',
                region: 'right',
                open: true,
                splitter: true,
                style: 'height:200px;',  
                collapsible: true,
                content: '<span><div id="testNode2"></div></span><div id="basemapGallery"></div>'
            },
basemapGallery: {
                include: true,
                id: 'basemapGallery',
                type: 'titlePane',
                title: 'Basemap Gallery',
                open: false,
                path: 'jimu/BaseWidgetPanel',
                sidebarID: 'sidebarRight',
                options: {
                    widgetManager: true,
                    config: {
                        widgets: [
                            {
                                id: 'WABBasemapGallery',
                                uri: 'wabwidgets/BasemapGallery/Widget'
                            }
                        ]
                    }
                }
            },

**Comment by tmcgee** [comment]
@cmccullough2 you need to use `placeAt: 'right'` in the widget configuration to put a widget in the right-hand pane. `sidebarID: 'sidebarRight'` is unnecessary in the widget configuration. You also do not need the style or content properties in configuration for the pane.

**Comment by cmccullough2** [comment]
I did what you suggested, but I am still getting this error below:  The rest of the error message is my local IP address.  Thoughts ...
![rightpane](https://cloud.githubusercontent.com/assets/3169799/18690072/f40c3714-7f51-11e6-8dbc-b52f30437809.PNG)

**Comment by tmcgee** [comment]
@cmccullough2 I have tested this in the wab demo configuration and it does work. The pane configuration looks like this:

``` javascript
panes: {
    left: {
        splitter: true,
        style: 'width:340px;'
    },
    right: {
        id: 'sidebarRight',
        placeAt: 'outer',
        region: 'right',
        collapsible: true
    }
},
```

and you only need add this to the BaseMapGallery widget's configuration:

``` javascript
placeAt: 'right'
```

**Comment by tmcgee** [comment]
@cmccullough2 For completeness, there is a new Basemap Gallery widget in CMV that works like a drop-down similar to the existing CMV Basemap widget. I prefer that to the WAB version which takes up so much screen real estate.

**Comment by cmccullough2** [comment]
Thank you.  I agree.  I can test it for you, but I am sure you have done it many times already.  Unfortunately, my 'idea fairy' wants to have a customized basemap with Google Terrain maps.  I have successfully done this, but not in a gallery style.  Hopefully, I can update my github site with the correct code, so I can share.  I have been incredibly busy with things not developer related.

**Comment by cmccullough2** [comment]
@tmcgee Is there a config for this widget?

**Comment by tmcgee** [comment]
For the new CMV BasemapGallery widget? There isn't a config documented explicitly, but you can extract it from the CMV code I added to include a BasemapGallery widget when a Webmap expects one: https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/_WebMapMixin.js#L139

**Comment by tmcgee** [comment]
You can also include `galleryOptions` like [this](https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/Basemaps.js#L52) which includes the parameters documented in the [Esri Basemap widget](https://developers.arcgis.com/javascript/3/jsapi/basemapgallery-amd.html).

You mentioned the Google Terrain map, the CMV BaseMapGallery widget should be able to include that mostly unchanged since the BaseMap widget has always used an Esri BaseMapGallery behind the scenes. Just include your array custom basemaps as the `basemaps` parameter within the galleryOptions. You'll need a thumbnail image, of course.
