### ISSUE TITLE
scriptError dojo loader //cdnjs.cloudflare.com/ajax/libs/xlsx/0.7.8/xlsx.core.min.js

### ISSUE THREAD

**Issue by cmccullough2** [tmcgee/cmv-wab-widgets#7]
I am having trouble with this error while on my work network.  Where is this js referenced?  How can I fix it?

**Comment by tmcgee** [comment]
@cmccullough2 That file is referenced by the Export widget: https://github.com/tmcgee/cmv-widgets/blob/master/widgets/Export.js#L434 It is used for exporting Excel and CSV files.

**Comment by cmccullough2** [comment]
that was it.  thanks
