### ISSUE TITLE
eDraw wab widget issue?

### ISSUE THREAD

**Issue by unknownids** [tmcgee/cmv-wab-widgets#8]
Can anyone try the eDraw widget and test if the export feature is working with the latest CMV from the dev branch? The import seems to be functioning but I cannot get the export dialog to trigger. 

Thanks!

**Comment by tmcgee** [comment]
@travisslack Are you referring to [this widget](https://geonet.esri.com/thread/122331-edraw-widget)? If so, exporting from their [demo](http://apps.magis.nc/maps/wab-widgets/?extent=17918900%2C-2706198%2C19092972%2C-2154016%2C102100) doesn't work so this likely an issue with the widget not specific to using it with CMV. I have not spent much time with that particular widget but exporting can often require some back-end script on the server. That may or may not be the case here.
