### ISSUE TITLE
Enhanced Search Widget Version 2.2 - 11/24/16

### ISSUE THREAD

**Issue by saurabhgis** [tmcgee/cmv-wab-widgets#9]
Hi
I m trying to configure enhanced esearch widget but facing some issues, might I m doing some configuration wrong.

Enhanced Search Widget Version 2.2 - 11/24/16

https://geonet.esri.com/docs/DOC-1731

**Comment by tmcgee** [comment]
same question asked in gitter room and response provided there so I am closing this issue
